import {notFound} from "next/navigation";
import chapters from "../../../../data/palestine-ar.json";
type Chapter=(typeof chapters)[number];
export function generateStaticParams(){return chapters.map(c=>({slug:c.slug}))}
export default async function PalestineChapterAr({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const chapter=chapters.find(c=>c.slug===slug) as Chapter|undefined;if(!chapter)notFound();const next=chapters[(chapters.findIndex(c=>c.slug===slug)+1)%chapters.length];return <main className="palestine-article ar-page" dir="rtl" lang="ar">
 <nav className="nav shell palestine-nav"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/ar">الرئيسية</a><a href="/ar/palestine">فلسطين</a><a href="/ar/gaza">غزة</a><a href={`/palestine/${chapter.slug}`}>English</a></div><a className="edition" href="/ar/palestine">كل الفصول <span>→</span></a></nav>
 <article><header className="palestine-article-head shell"><p><span>فلسطين / {chapter.number}</span><b>تاريخ ومنظور</b></p><div className="eyebrow"><span/> {chapter.eyebrow}</div><h1>{chapter.title}</h1><p className="palestine-dek">{chapter.dek}</p></header>
 <figure className="palestine-photo shell"><img src={chapter.image} alt={chapter.imageAlt}/><figcaption><span>{chapter.imageAlt}</span><a href={chapter.imagePage} target="_blank" rel="noreferrer">{chapter.imageCredit} ↗</a></figcaption></figure>
 <div className="palestine-story shell"><aside><span>موقفنا</span><blockquote>«{chapter.quote}»</blockquote><a href="/ar/palestine">عن هذا الدليل ←</a></aside><div className="palestine-copy">{chapter.paragraphs.slice(0,2).map((p,i)=><p className={i===0?"first-paragraph":""} key={p}>{p}</p>)}<div className="palestine-facts">{chapter.facts.map(f=><div key={f[1]}><b>{f[0]}</b><span>{f[1]}</span></div>)}</div>{chapter.paragraphs.slice(2).map(p=><p key={p}>{p}</p>)}<section className="palestine-sources"><b>المصادر وقراءة إضافية</b>{chapter.sources.map(s=><a href={s[1]} target="_blank" rel="noreferrer" key={s[1]}>{s[0]} <span>↗</span></a>)}</section><div className="palestine-method"><b>ملاحظة تحريرية</b><p>ينطلق هذا الفصل من منظور فلسطيني لحقوق الإنسان. وحين تختلف المؤسسات، خاصة حول الإبادة والقدس، نحدد الجهة صاحبة النتيجة ووضعها القانوني.</p></div></div></div></article>
 <a className="next-palestine shell" href={`/ar/palestine/${next.slug}`}><span>الفصل التالي</span><h2>{next.title}</h2><b>تابع ↖</b></a><footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>فلسطين، قصة كاملة.</p><p>© 2026 وورلدلاين</p></footer></main>}
