import type { Metadata } from "next";

export const metadata:Metadata={title:"Worldline Kids — Palestine & Gaza Storybook",description:"A gentle illustrated children's story about Palestine, Gaza, memory and hope, with a free English PDF."};
const chapters=[
  {n:"01",title:"The land remembers",text:"Lina and Omar walk with Grandmother among olive and fig trees. She tells them about Palestinian cities, villages, farms and family traditions carried across generations.",image:"/images/kids/olive-jerusalem.jpg"},
  {n:"02",title:"The key tells a story",text:"A brass key opens a conversation about the 1948 Nakba, when around 750,000 Palestinians were displaced. The story explains memory and loss gently, without frightening pictures.",image:"/images/kids/memory-key.jpg"},
  {n:"03",title:"Gaza plants tomorrow",text:"At Gaza's Mediterranean shore, children fly kites, repair a school and plant a young olive tree—a picture of ordinary life, dignity and hope.",image:"/images/kids/gaza-hope.jpg"}
];
export default function KidsPage(){return <main className="kids-page">
  <nav className="nav shell kids-nav"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="#story">The story</a><a href="#grownups">For grown-ups</a><a href="/palestine">Palestine</a><a href="/gaza">Gaza</a></div><a className="edition" href="/ar/kids">العربية ↗</a></nav>
  <header className="kids-hero"><img src="/images/kids/olive-jerusalem.jpg" alt="Lina, Omar and their grandmother beneath an olive tree overlooking Al-Quds"/><div className="kids-hero-shade"/><div className="shell kids-hero-copy"><p>WORLDLINE KIDS · AGES 7-11</p><h1>Lina, Omar<br/>& the <em>Olive Tree</em></h1><span>A gentle illustrated journey through Palestine, Gaza, memory and hope.</span><div><a href="/downloads/worldline-kids-palestine-gaza-en.pdf" download>Download English PDF <b>↓</b></a><a href="/downloads/worldline-kids-palestine-gaza-ar.pdf" download>النسخة العربية <b>↓</b></a></div></div></header>
  <section className="kids-intro shell" id="story"><p className="eyebrow"><span/> Read together</p><div><h2>A difficult history,<br/><em>told with care.</em></h2><p>This child-friendly story introduces Palestinian history, Al-Quds, the Nakba, cultural life and Gaza. It tells the truth without graphic scenes and always reminds young readers that every child deserves safety and dignity.</p></div></section>
  <section className="kids-chapters">{chapters.map((c,i)=><article className="shell kids-chapter" key={c.n}><div className="kids-chapter-image"><img src={c.image} alt=""/></div><div><span>{c.n} / 03</span><h2>{c.title}</h2><p>{c.text}</p><i>{i===2?"Freedom · dignity · safety · equal rights":"Memory · family · belonging"}</i></div></article>)}</section>
  <section className="kids-grownups" id="grownups"><div className="shell"><div><p className="eyebrow light"><span/> Parent & teacher note</p><h2>Pause. Listen.<br/>Let children ask.</h2></div><div><p>The PDF is a gentle introduction, not a complete history. It includes a final sources page pointing families to the United Nations, UNRWA, UNICEF and UNESCO for deeper or updated reading.</p><ul><li><b>01</b> No graphic or frightening imagery</li><li><b>02</b> Clear distinction between history and hope</li><li><b>03</b> Original cartoon illustrations</li><li><b>04</b> Free English and Arabic editions</li></ul><a href="/downloads/worldline-kids-palestine-gaza-en.pdf" download>Get the 9-page book ↓</a></div></div></section>
  <footer className="footer shell"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><p>Stories that help young readers remember, wonder and care.</p><p>© 2026 Worldline Kids</p></footer>
  </main>}
