import WarDotMap from "../components/WarDotMap";
import LiveWarNews from "../components/LiveWarNews";

export const metadata={title:"Iran–Israel–U.S. War Live — Worldline",description:"Live sourced reporting and an editorial country exposure map for the Iran–Israel–U.S. war."};
const groups=[
 {className:"red",label:"Very high escalation",countries:"Iran · Israel · United States · Lebanon · Yemen",note:"Direct belligerents or active connected fronts."},
 {className:"orange",label:"Medium",countries:"Jordan · Iraq · Saudi Arabia · Kuwait · Bahrain · Qatar · UAE",note:"Reported strikes, bases, shipping or critical-infrastructure exposure."},
 {className:"yellow",label:"Limited",countries:"Oman · Syria · Türkiye · Egypt · Pakistan",note:"Border, airspace, energy or mediation spillover."},
 {className:"gray",label:"Normal / not included",countries:"All other countries",note:"Not classified in this focused regional tracker."}
];
export default function WarPage(){return <main className="war-page">
 <nav className="nav shell war-nav"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/">Home</a><a className="active" href="/war">War live</a><a href="/date">By date</a><a href="/palestine">Palestine</a><a href="/gaza">Gaza</a></div><a className="edition" href="/ar/war">العربية <span>↗</span></a></nav>
 <header className="war-hero shell"><div><p className="eyebrow"><span/> Live regional desk · 20 July 2026</p><h1>Iran–Israel–U.S.<br/><em>war, live.</em></h1><p>Fast updates with visible sourcing, a regional exposure map, and attention to civilians across Iran, Palestine, Lebanon, Yemen and the wider Arab region.</p><a href="#live">Open live updates ↓</a></div><aside><b><i/> CURRENT SIGNAL</b><h2>Fighting widens as mediators float a 10-day ceasefire.</h2><p>Reuters reports a ninth consecutive night of U.S. strikes, Iranian retaliation and a Houthi threat to open another maritime front.</p><a href="https://www.reuters.com/world/middle-east/us-launches-iran-strikes-ninth-day-another-american-confirmed-killed-2026-07-20/" target="_blank" rel="noreferrer">Read the source ↗</a></aside></header>
 <section className="war-map-section"><div className="shell"><div className="war-map-head"><div><p className="eyebrow light"><span/> Country exposure map</p><h2>A dotted world,<br/><em>colored by escalation.</em></h2></div><p>These are Worldline editorial exposure levels based on direct combat, reported strikes, military bases, shipping routes and immediate spillover. They are not travel advice or a prediction.</p></div><div className="war-map-frame"><WarDotMap/><span>20 JUL · 2026</span></div><div className="war-legend">{groups.map(g=><article className={g.className} key={g.className}><i/><small>{g.label}</small><h3>{g.countries}</h3><p>{g.note}</p></article>)}</div></div></section>
 <section className="war-live shell" id="live"><div className="section-heading"><div><p className="eyebrow"><span/> Automatic feed · 5 minute cache</p><h2>The latest reports.</h2></div><p>Headlines are pulled from the open GDELT index, with Google News RSS and a verified July 20 snapshot as fallbacks. Links open at the original publisher.</p></div><LiveWarNews lang="en"/></section>
 <section className="war-sources"><div className="shell"><div><b>VERIFIED SNAPSHOT</b><h2>What is confirmed now.</h2></div><ol><li><span>01</span><p>Reuters reports mediators proposed a 10-day ceasefire to revive the Iran–U.S. interim deal.</p><a href="https://www.reuters.com/world/middle-east/mediators-propose-10-day-ceasefire-revive-iran-us-interim-deal-senior-iranian-2026-07-20/" target="_blank" rel="noreferrer">Reuters ↗</a></li><li><span>02</span><p>AP identified two U.S. soldiers killed in Iranian attacks in Jordan.</p><a href="https://apnews.com/article/1fd99826dfd511913b63d0b033b262d9" target="_blank" rel="noreferrer">AP ↗</a></li><li><span>03</span><p>The UN Secretary-General has urged Iran and the United States to return urgently to diplomacy.</p><a href="https://www.un.org/sg/en/content/highlight/2026-07-13.html" target="_blank" rel="noreferrer">United Nations ↗</a></li></ol></div></section>
 <section className="war-method shell"><b>Map method</b><p>The map is deliberately broad and editorial. Red means direct belligerency or an active connected front; orange means reported military, infrastructure or shipping exposure; yellow means limited spillover or mediation proximity; gray means outside this tracker. Country coloring does not imply equal danger within every location.</p></section>
 <footer className="footer shell"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><p>Civilians first. Sources visible.</p><p>© 2026 Worldline Journal</p></footer>
 </main>}
