type Story={number:string;slug:string;category:string;title:string;dek:string;date:string;readTime:string};
export default function DateEdition({stories,dateKey,lang}:{stories:Story[];dateKey:string;lang:"en"|"ar"}){
  const ar=lang==="ar"; const older=dateKey==="2026-07-18"?"2026-07-17":null; const newer=dateKey==="2026-07-17"?"2026-07-18":null;
  return <main className={`date-page ${ar?"ar-page":""}`} dir={ar?"rtl":"ltr"} lang={lang}>
    <nav className="nav shell date-nav"><a className="brand" href={ar?"/ar":"/"}>WORLD<span>LINE</span><i/></a><div className="nav-links"><a href={ar?"/ar#latest":"/#latest"}>{ar?"الأحدث":"Latest"}</a><a href={ar?"/ar/date":"/date"}>{ar?"كل التواريخ":"All dates"}</a><a href={ar?"/ar/research":"/research"}>{ar?"الأبحاث":"Research"}</a></div><a className="edition" href={ar?`/date/${dateKey}`:`/ar/date/${dateKey}`}>{ar?"English":"العربية"} ↗</a></nav>
    <header className="date-edition-hero shell"><div><p className="eyebrow"><span/>{ar?"إصدار يومي موثق":"A sourced daily edition"}</p><h1>{dateKey.slice(8)}<br/><em>{ar?"يوليو":"July"}</em><br/>2026</h1></div><aside><b>{ar?"10 قصص":"10 STORIES"}</b><p>{ar?"صورة واضحة لأهم ما حدث في هذا اليوم، مع صفحة كاملة ومصدر أصلي لكل قصة.":"A clear record of what mattered on this day, with a complete page and original source for every story."}</p><a href={ar?"/ar/date":"/date"}>{ar?"افتح أرشيف التواريخ":"Open date archive"} ↗</a></aside></header>
    <section className="dated-stories shell"><div className="dated-stories-head"><p>{ar?"إصدار اليوم":"THE DAILY EDITION"}</p><time dateTime={dateKey}>{stories[0]?.date}</time></div>{stories.map(s=><a href={`${ar?"/ar":""}/news/${s.slug}`} className="dated-story" key={s.slug}><span>{s.number}</span><div><b>{s.category}</b><h2>{s.title}</h2><p>{s.dek}</p></div><i>{s.readTime}<strong>↗</strong></i></a>)}</section>
    <section className="date-step"><div className="shell"><div>{newer?<a href={`${ar?"/ar":""}/date/${newer}`}><span>{ar?"الإصدار الأحدث":"Newer edition"}</span><b>18 {ar?"يوليو":"July"} 2026 ↗</b></a>:<span/>}</div><a href={ar?"/ar/date":"/date"}><span>{ar?"تصفح":"Browse"}</span><b>{ar?"كل التواريخ":"All dates"} ↗</b></a><div>{older?<a href={`${ar?"/ar":""}/date/${older}`}><span>{ar?"الإصدار السابق":"Previous edition"}</span><b>17 {ar?"يوليو":"July"} 2026 ↗</b></a>:<span/>}</div></div></section>
    <footer className="footer shell"><a className="brand" href={ar?"/ar":"/"}>WORLD<span>LINE</span><i/></a><p>{ar?"أرشيف يومي، بسياق ومصادر.":"A daily archive with context and sources."}</p><p>© 2026 Worldline</p></footer>
  </main>
}
