import news from "../../data/news-ar.json";
import DotGlobe from "../components/DotGlobe";
const Arrow=()=> <span aria-hidden="true">↖</span>;
export const metadata={title:"وورلدلاين — الأخبار في سياقها",description:"قصص مستقلة وسياق عالمي وأفكار تستحق وقتك."};
export default function ArabicHome(){const lead=news[0];return <main className="ar-page" dir="rtl" lang="ar">
<section className="hero" id="top"><nav className="nav shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="#latest">الأحدث</a><a href="/ar/palestine">فلسطين</a><a href="/ar/gaza">غزة</a><a href="/">English</a></div><a className="edition" href="#latest">أحدث 10 قصص <span>↙</span></a></nav>
<div className="hero-grid shell"><div className="hero-copy"><p className="eyebrow"><span/> قصص مستقلة لعالم مترابط</p><h1>العالم،<br/><em>بمنظور أوضح.</em></h1><p className="dek">أخبار بعمق وسياق ووجهة نظر. مكان واحد واضح لفهم ما يهم ولماذا يهم الآن.</p><div className="hero-actions"><a className="button button-dark" href="#latest">اكتشف قصص اليوم <Arrow/></a><a className="text-link" href="#newsletter">النشرة الصباحية <span>←</span></a></div></div>
<div className="globe-stage"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="globe-shadow"/><div className="globe"><DotGlobe /></div><div className="globe-note note-top"><b>24:00</b><span>القصص لا تتوقف</span></div><div className="globe-note note-bottom"><b>عالمي</b><span>تغطية بلا حدود</span></div></div>
<aside className="brief-card"><div className="brief-head"><p><span className="live-dot"/> القصة الرئيسية</p><time>17 يوليو 2026</time></div><a className="brief-lead" href={`/ar/news/${lead.slug}`}><span>{lead.category} / الأحدث</span><h2>{lead.title}</h2><p>{lead.dek}</p><i><Arrow/></i></a><div className="brief-ticker"><span>اليوم</span><p>عشر قصص أساسية في إصدار واضح</p><b>10</b></div></aside></div>
<div className="topic-strip shell"><span>تابع القصة</span><a href="#latest">المناخ</a><a href="#latest">الذكاء الاصطناعي</a><a href="#latest">الأسواق</a><a href="#latest">العلوم والفضاء</a><a className="all-topics" href="#latest">كل القصص <Arrow/></a></div></section>
<section className="latest shell" id="latest"><div className="section-heading"><div><p className="eyebrow"><span/> تحديث 17 يوليو 2026</p><h2>أحدث عشر قصص.</h2></div><p>عشر قصص حالية في الشؤون العالمية والتكنولوجيا والعلوم والمناخ والأعمال، ولكل قصة صفحتها الكاملة.</p></div><div className="story-list">{news.map(s=><a className="story-row" href={`/ar/news/${s.slug}`} key={s.slug}><span className="story-number">{s.number}</span><span className="story-category">{s.category}</span><h3>{s.title}</h3><span className="story-time">{s.readTime}</span><span className="story-arrow"><Arrow/></span></a>)}</div></section>
<section className="home-palestine"><div className="shell home-palestine-grid"><div><p className="eyebrow light"><span/> دليل تاريخي جديد</p><h2>فلسطين،<br/><em>قصة كاملة.</em></h2></div><p>دليل من ستة فصول تقوده الخريطة: التاريخ والنكبة والحياة اليومية والقدس والزيتون والتين وغزة، من منظور فلسطيني.</p><a href="/ar/palestine">استكشف فلسطين <span>↖</span></a></div></section>
<section className="home-gaza"><div className="shell home-gaza-grid"><div><p className="eyebrow light"><span/> سلسلة رأي جديدة</p><h2>غزة: حياة،<br/><em>حقوق، عودة.</em></h2></div><p>خمس مقالات تضع المدنيين الفلسطينيين والتعليم والمساعدات والإعمار والذاكرة الثقافية في المركز، مع رسوم موثقة وصور صحفية.</p><a href="/ar/gaza">استكشف سلسلة غزة <span>↖</span></a></div></section>
<section className="manifesto"><div className="shell manifesto-grid"><p className="eyebrow light"><span/> وجهة نظرنا</p><blockquote>«أفضل الأخبار لا تخبرك بما تفكر، بل تمنحك المزيد لتفكر فيه.»</blockquote><a href="#latest">اقرأ الإصدار <Arrow/></a></div></section>
<section className="newsletter shell" id="newsletter"><div><p className="eyebrow"><span/> ابدأ يومك بمعرفة</p><h2>رسالة واحدة جيدة.<br/>كل صباح.</h2></div><form className="signup-form"><label htmlFor="email">البريد الإلكتروني</label><div><input id="email" type="email" placeholder="you@example.com"/><button type="button">انضم للنشرة <span>←</span></button></div><small>بلا ضوضاء، فقط أهم قصص اليوم.</small></form></section>
<footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>صحافة مستقلة للعقول الفضولية.</p><p>© 2026 وورلدلاين</p></footer></main>}