import news from "../../data/news-ar.json";
import DotGlobe from "../components/DotGlobe";
import NewsletterForm from "../components/NewsletterForm";
const Arrow=()=> <span aria-hidden="true">↖</span>;
export const metadata={title:"وورلدلاين — الأخبار في سياقها",description:"قصص مستقلة وسياق عالمي وأفكار تستحق وقتك."};
export default function ArabicHome(){const lead=news[0];return <main className="ar-page" dir="rtl" lang="ar">
<section className="hero" id="top"><nav className="nav shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="#latest">الأحدث</a><a href="/ar/war">الحرب مباشر</a><a href="/ar/date">حسب التاريخ</a><a href="/ar/wlb">WLB</a><a href="/ar/kids">للأطفال</a><a href="/ar/ai">AI</a><a href="/ar/research">الأبحاث</a><a href="/ar/palestine">فلسطين</a><a href="/ar/gaza">غزة</a><a href="/ar/about">عن الموقع</a></div><a className="edition" href="/ar/date/2026-07-18">إصدار 18 يوليو <span>↙</span></a></nav>
<div className="hero-grid shell"><div className="hero-copy"><p className="eyebrow"><span/> قصص مستقلة لعالم مترابط</p><h1>العالم،<br/><em>بمنظور أوضح.</em></h1><p className="dek">أخبار بعمق وسياق ووجهة نظر. مكان واحد واضح لفهم ما يهم ولماذا يهم الآن.</p><div className="hero-actions"><a className="button button-dark" href="#latest">اكتشف قصص اليوم <Arrow/></a><a className="text-link" href="#newsletter">النشرة الصباحية <span>←</span></a></div></div>
<div className="globe-stage"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="globe-shadow"/><div className="globe"><DotGlobe /></div><div className="globe-note note-top"><b>24:00</b><span>القصص لا تتوقف</span></div><div className="globe-note note-bottom"><b>عالمي</b><span>تغطية بلا حدود</span></div></div>
<aside className="brief-card"><div className="brief-head"><p><span className="live-dot"/> القصة الرئيسية</p><time>18 يوليو 2026</time></div><a className="brief-lead" href={`/ar/news/${lead.slug}`}><span>{lead.category} / الأحدث</span><h2>{lead.title}</h2><p>{lead.dek}</p><i><Arrow/></i></a><div className="brief-ticker"><span>اليوم</span><p>عشر قصص أساسية في إصدار واضح</p><b>10</b></div></aside></div>
<div className="topic-strip shell"><span>مكتب الأبحاث</span><a href="/ar/research/palestine">فلسطين</a><a href="/ar/research/sudan">السودان</a><a href="/ar/research/african-hunger">الجوع في أفريقيا</a><a href="/ar/research/trump">ترامب</a><a href="/ar/research/netanyahu">نتنياهو</a><a className="all-topics" href="/ar/research">كل الملفات <Arrow/></a></div></section>
<section className="latest shell" id="latest"><div className="section-heading"><div><p className="eyebrow"><span/> تحديث 18 يوليو 2026 · <a href="/ar/date">حسب التاريخ</a></p><h2>أحدث عشر قصص.</h2></div><p>عشر قصص حالية في الشؤون العالمية والتكنولوجيا والعلوم والمناخ والأعمال، ولكل قصة صفحتها الكاملة.</p></div><div className="story-list">{news.map(s=><a className="story-row" href={`/ar/news/${s.slug}`} key={s.slug}><span className="story-number">{s.number}</span><span className="story-category">{s.category}</span><h3>{s.title}</h3><span className="story-time">{s.readTime}</span><span className="story-arrow"><Arrow/></span></a>)}</div></section>
<section className="home-war"><div className="shell home-war-grid"><div><p className="eyebrow light"><span/> مكتب مباشر · تحديث كل 5 دقائق</p><h2>حرب إيران وإسرائيل وأميركا،<br/><em>على الخريطة.</em></h2></div><p>عناوين مباشرة بمصادرها وخريطة عالمية من النقاط تعرض التصعيد المباشر والانكشاف الإقليمي والتداعيات المحدودة.</p><a href="/ar/war">افتح مكتب الحرب ↖</a></div></section>\n<section className="home-ai"><div className="shell home-ai-grid"><div><p className="eyebrow"><span/> تغذية تلقائية مباشرة</p><h2>أخبار AI،<br/><em>تحدّث نفسها.</em></h2></div><p>أحدث التقارير عن النماذج والأبحاث والسياسات والشركات، من قاعدة أخبار عالمية مفتوحة كل 15 دقيقة.</p><a href="/ar/ai">افتح مكتب AI <span>↖</span></a></div></section>
<section className="home-research"><div className="shell"><div className="home-research-head"><div><p className="eyebrow light"><span/> بحث عميق · تحقق 18 يوليو 2026</p><h2>ذاكرة،<br/><em>مع الدليل.</em></h2></div><p>خمسة ملفات موثقة من منظور عربي وفلسطيني: موقف واضح ودقة في وصف الأدلة.</p><a href="/ar/research">افتح مكتب الأبحاث ↖</a></div><div className="home-research-list"><a href="/ar/research/palestine"><span>01</span><b>فلسطين</b><i>القانون والأرض والحياة ↖</i></a><a href="/ar/research/sudan"><span>02</span><b>السودان</b><i>المدنيون قبل الجنرالات ↖</i></a><a href="/ar/research/african-hunger"><span>03</span><b>الجوع في أفريقيا</b><i>المجاعات تُصنع ↖</i></a><a href="/ar/research/trump"><span>04</span><b>ترامب</b><i>القوة وفلسطين ↖</i></a><a href="/ar/research/netanyahu"><span>05</span><b>نتنياهو</b><i>القيادة والمساءلة ↖</i></a></div></div></section>
<section className="home-palestine"><div className="shell home-palestine-grid"><div><p className="eyebrow light"><span/> دليل تاريخي جديد</p><h2>فلسطين،<br/><em>قصة كاملة.</em></h2></div><p>دليل من ستة فصول تقوده الخريطة: التاريخ والنكبة والحياة اليومية والقدس والزيتون والتين وغزة، من منظور فلسطيني.</p><a href="/ar/palestine">استكشف فلسطين <span>↖</span></a></div></section>
<section className="home-gaza"><div className="shell home-gaza-grid"><div><p className="eyebrow light"><span/> سلسلة رأي جديدة</p><h2>غزة: حياة،<br/><em>حقوق، عودة.</em></h2></div><p>خمس مقالات تضع المدنيين الفلسطينيين والتعليم والمساعدات والإعمار والذاكرة الثقافية في المركز، مع رسوم موثقة وصور صحفية.</p><a href="/ar/gaza">استكشف سلسلة غزة <span>↖</span></a></div></section>
<section className="manifesto"><div className="shell manifesto-grid"><p className="eyebrow light"><span/> وجهة نظرنا</p><blockquote>«أفضل الأخبار لا تخبرك بما تفكر، بل تمنحك المزيد لتفكر فيه.»</blockquote><a href="#latest">اقرأ الإصدار <Arrow/></a></div></section>
<section className="newsletter shell" id="newsletter"><div><p className="eyebrow"><span/> يُرسل عبر Gmail</p><h2>موجز اليوم،<br/>في بريدك.</h2></div><NewsletterForm lang="ar"/></section>
<footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>صحافة مستقلة للعقول الفضولية. <a href="/ar/about">عن VOAI ↖</a></p><p>© 2026 وورلدلاين</p></footer></main>}