import {notFound} from "next/navigation";
import chapters from "../../../data/palestine.json";
type Chapter=(typeof chapters)[number];
export function generateStaticParams(){return chapters.map(c=>({slug:c.slug}))}
export default async function PalestineChapter({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const chapter=chapters.find(c=>c.slug===slug) as Chapter|undefined;if(!chapter)notFound();const next=chapters[(chapters.findIndex(c=>c.slug===slug)+1)%chapters.length];return <main className="palestine-article">
 <nav className="nav shell palestine-nav"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/">Home</a><a href="/palestine">Palestine</a><a href="/gaza">Gaza</a><a href={`/ar/palestine/${chapter.slug}`}>العربية</a></div><a className="edition" href="/palestine">All chapters <span>←</span></a></nav>
 <article><header className="palestine-article-head shell"><p><span>Palestine / {chapter.number}</span><b>History & perspective</b></p><div className="eyebrow"><span/> {chapter.eyebrow}</div><h1>{chapter.title}</h1><p className="palestine-dek">{chapter.dek}</p></header>
 <figure className="palestine-photo shell"><img src={chapter.image} alt={chapter.imageAlt}/><figcaption><span>{chapter.imageAlt}</span><a href={chapter.imagePage} target="_blank" rel="noreferrer">{chapter.imageCredit} ↗</a></figcaption></figure>
 <div className="palestine-story shell"><aside><span>Our position</span><blockquote>“{chapter.quote}”</blockquote><a href="/palestine">About this guide →</a></aside><div className="palestine-copy">{chapter.paragraphs.slice(0,2).map((p,i)=><p className={i===0?"first-paragraph":""} key={p}>{p}</p>)}<div className="palestine-facts">{chapter.facts.map(f=><div key={f[1]}><b>{f[0]}</b><span>{f[1]}</span></div>)}</div>{chapter.paragraphs.slice(2).map(p=><p key={p}>{p}</p>)}<section className="palestine-sources"><b>Sources & further reading</b>{chapter.sources.map(s=><a href={s[1]} target="_blank" rel="noreferrer" key={s[1]}>{s[0]} <span>↗</span></a>)}</section><div className="palestine-method"><b>Editorial note</b><p>This chapter argues from a Palestinian human-rights perspective. Where institutions differ—especially on genocide and Jerusalem—the text identifies the finding and its legal status.</p></div></div></div></article>
 <a className="next-palestine shell" href={`/palestine/${next.slug}`}><span>Next chapter</span><h2>{next.title}</h2><b>Continue ↗</b></a><footer className="footer shell"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><p>Palestine remembered whole.</p><p>© 2026 Worldline Journal</p></footer></main>}
