export const metadata={title:"The True Story: Gaza in photographs — Worldline",description:"A warned, source-attributed documentary record of injury, death and destroyed homes in Gaza."};
const images=[
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Damage%20in%20Gaza%20Strip%20during%20the%20October%202023%20-%2029.jpg",alt:"Palestinians walk among homes destroyed by an Israeli airstrike in the El-Remal area of Gaza City",title:"The house after the bomb",caption:"Damage in Gaza City’s El-Remal area after an Israeli airstrike, 9 October 2023.",credit:"Naaman Omar / APAimages via Wikimedia Commons",page:"https://commons.wikimedia.org/wiki/File:Damage_in_Gaza_Strip_during_the_October_2023_-_29.jpg",kind:"Destroyed homes"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Fars%20Photo%20of%20Casualties%20in%20Gaza%20Strip%20during%202023%20War%2031.jpg",alt:"An injured Palestinian child after Israeli airstrikes in Gaza",title:"A child is not a statistic",caption:"An injured Palestinian child in Gaza, photographed in October 2023.",credit:"Ghassan Salem / Fars Media via Wikimedia Commons, CC BY 4.0",page:"https://commons.wikimedia.org/wiki/File:Fars_Photo_of_Casualties_in_Gaza_Strip_during_2023_War_31.jpg",kind:"Blood and injury"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Relatives%20of%20Palestinians%20who%20died%20in%20Israeli%20airstrikes%20gathering%20around%20the%20bodies%20taken%20from%20the%20morgue%20of%20Al-Aqsa%20Martyrs%20hospital%20in%20Deir%20el-Balah%2C%20Gaza.jpg",alt:"Bereaved Palestinian relatives gather around covered bodies outside Al-Aqsa Martyrs Hospital in Deir el-Balah",title:"The dead leave families behind",caption:"Relatives gather around bodies taken from the morgue of Al-Aqsa Martyrs Hospital, Deir el-Balah, 6 November 2023.",credit:"Ashraf Amra / UNRWA via Wikimedia Commons, CC BY-SA 4.0",page:"https://commons.wikimedia.org/wiki/File:Relatives_of_Palestinians_who_died_in_Israeli_airstrikes_gathering_around_the_bodies_taken_from_the_morgue_of_Al-Aqsa_Martyrs_hospital_in_Deir_el-Balah,_Gaza.jpg",kind:"Covered bodies and grief"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Images%20of%20war%2023-25%20from%20Gaza%2C%20by%20Jaber%20Badwen%2C%20IMG%206185.jpg",alt:"Ruins of homes in Beit Lahia destroyed by Israeli bombardment",title:"A neighbourhood turned to rubble",caption:"Ruins of Beit Lahia in northern Gaza, photographed on 23 February 2025.",credit:"Jaber Jehad Badwan via Wikimedia Commons",page:"https://commons.wikimedia.org/wiki/File:Images_of_war_23-25_from_Gaza,_by_Jaber_Badwen,_IMG_6185.jpg",kind:"Bombed neighbourhood"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Damage%20in%20Gaza%20Strip%20during%20the%20October%202023%20-%2006.jpg",alt:"Palestinians inspect the ruins of Watan Tower after Israeli airstrikes in Gaza City",title:"Where families once lived",caption:"Palestinians inspect Watan Tower after its destruction in Israeli airstrikes, Gaza City, 8 October 2023.",credit:"Naaman Omar / APAimages via Wikimedia Commons",page:"https://commons.wikimedia.org/wiki/File:Damage_in_Gaza_Strip_during_the_October_2023_-_06.jpg",kind:"Destroyed residential tower"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Fars%20Photo%20of%20Casualties%20in%20Gaza%20Strip%20during%202023%20War%2026.jpg",alt:"A medic carries a wounded Palestinian child in Gaza",title:"Carried toward care",caption:"A medic carries a wounded Palestinian child in Gaza in October 2023.",credit:"Ghassan Salem / Fars Media via Wikimedia Commons, CC BY 4.0",page:"https://commons.wikimedia.org/wiki/File:Fars_Photo_of_Casualties_in_Gaza_Strip_during_2023_War_26.jpg",kind:"Wounded child"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Fars%20Photo%20of%20Casualties%20in%20Gaza%20Strip%20during%202023%20War%2003.jpg",alt:"Palestinians killed in Gaza lie in covered body bags",title:"Lives ended, names remembered",caption:"Covered bodies in Gaza following mass casualties in October 2023.",credit:"Saleh Najm and Anas Al-Sharif / Fars Media via Wikimedia Commons, CC BY 4.0",page:"https://commons.wikimedia.org/wiki/File:Fars_Photo_of_Casualties_in_Gaza_Strip_during_2023_War_03.jpg",kind:"Covered bodies"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Forced%20Displacement%20of%20Gaza%20Strip%20Residents%20During%20the%20Gaza-Israel%20War%2023-25.jpg",alt:"Displaced Palestinian families move through a Gaza landscape devastated by bombardment",title:"Forced from one ruin to another",caption:"Palestinians displaced through a devastated part of Gaza, 29 January 2025.",credit:"Jaber Jehad Badwan via Wikimedia Commons",page:"https://commons.wikimedia.org/wiki/File:Forced_Displacement_of_Gaza_Strip_Residents_During_the_Gaza-Israel_War_23-25.jpg",kind:"Forced displacement"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Palestine%20Red%20Crescent%20Society%27s%20ambulance%20after%20being%20targeted%20by%20Israeli%20missile%20in%20Khan%20Yunis.png",alt:"A heavily damaged Palestine Red Crescent ambulance outside Nasser Hospital in Khan Younis",title:"Even the ambulance was struck",caption:"A Palestine Red Crescent ambulance damaged outside Nasser Hospital in Khan Younis on 7 October 2023.",credit:"Tasnim footage via Wikimedia Commons",page:"https://commons.wikimedia.org/wiki/File:Palestine_Red_Crescent_Society%27s_ambulance_after_being_targeted_by_Israeli_missile_in_Khan_Yunis.png",kind:"Damaged medical transport"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Israeli%20destruction%20on%20al-Seqaly%20Street%20in%20Khan%20Younis%2C%20Gaza%20War%2C%20June%2011%202024.jpg",alt:"Destroyed buildings and rubble on al-Seqaly Street in Khan Younis",title:"A street erased",caption:"Destruction on al-Seqaly Street in Khan Younis, photographed on 11 June 2024.",credit:"Rawanmurad2025 via Wikimedia Commons",page:"https://commons.wikimedia.org/wiki/File:Israeli_destruction_on_al-Seqaly_Street_in_Khan_Younis,_Gaza_War,_June_11_2024.jpg",kind:"Destroyed street"}
];
export default function TrueStory(){return <main className="truth-page">
 <nav className="nav shell truth-nav"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/">Home</a><a href="/palestine">Palestine</a><a href="/gaza">Gaza</a><a href="/ar/palestine/the-true-story">العربية</a></div><a className="edition" href="/palestine">Back to guide <span>←</span></a></nav>
 <header className="truth-head shell"><p className="eyebrow"><span/> A documentary record</p><h1>The true story<br/><em>has witnesses.</em></h1><p>These photographs show what words can soften: blood, injured children, bodies returned to families, and homes reduced to rubble in Gaza.</p><div className="truth-warning"><b>Graphic content warning</b><span>This page contains documentary images of blood, injured children and covered bodies. Continue only if you choose to see them.</span></div></header>
 <section className="truth-context shell"><b>Why publish these images?</b><p>Not to shock for its own sake. The dead and wounded are people, not visual evidence to be consumed. We publish a limited, attributed record because sanitized language can hide the human result of bombardment. Captions identify only what the source supports.</p></section>
 <details className="truth-reveal shell"><summary><span>I understand — reveal the documentary images</span><b>Open record ↓</b></summary><div className="truth-gallery">{images.map((img,i)=><figure className="truth-image" key={img.src}><div><img src={img.src} alt={img.alt}/><span>{String(i+1).padStart(2,"0")} / {img.kind}</span></div><figcaption><h2>{img.title}</h2><p>{img.caption}</p><a href={img.page} target="_blank" rel="noreferrer">{img.credit} ↗</a></figcaption></figure>)}</div></details>
 <section className="truth-close shell"><p className="eyebrow"><span/> Remember the person</p><blockquote>Every body was someone’s child, parent, sibling, friend or neighbour. Every ruined house held a life larger than the rubble.</blockquote><a href="/palestine/gaza-genocide-and-the-duty-to-protect">Read the sourced Gaza chapter ↗</a></section>
 <footer className="footer shell"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><p>Documented with dignity.</p><p>© 2026 Worldline Journal</p></footer>
 </main>}
