import WarDotMap from "../../components/WarDotMap";
import LiveWarNews from "../../components/LiveWarNews";

export const metadata={title:"حرب إيران وإسرائيل وأميركا مباشر — وورلدلاين",description:"أخبار موثقة مباشرة وخريطة نقطية لمستويات انكشاف الدول على حرب إيران وإسرائيل والولايات المتحدة."};
const groups=[
 {className:"red",label:"متصاعد جداً",countries:"إيران · إسرائيل · الولايات المتحدة · لبنان · اليمن",note:"أطراف مباشرة أو جبهات نشطة متصلة بالحرب."},
 {className:"orange",label:"متوسط",countries:"الأردن · العراق · السعودية · الكويت · البحرين · قطر · الإمارات",note:"انكشاف لضربات أو قواعد أو شحن أو بنية تحتية حيوية."},
 {className:"yellow",label:"قليل",countries:"عُمان · سوريا · تركيا · مصر · باكستان",note:"تداعيات محدودة على الحدود أو الأجواء أو الطاقة أو الوساطة."},
 {className:"gray",label:"طبيعي / غير مشمول",countries:"جميع الدول الأخرى",note:"ليست مصنفة ضمن هذا المتتبع الإقليمي المحدد."}
];
export default function WarPageAr(){return <main className="war-page ar-page" dir="rtl" lang="ar">
 <nav className="nav shell war-nav"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/ar">الرئيسية</a><a className="active" href="/ar/war">الحرب مباشر</a><a href="/ar/date">حسب التاريخ</a><a href="/ar/palestine">فلسطين</a><a href="/ar/gaza">غزة</a></div><a className="edition" href="/war">English <span>↖</span></a></nav>
 <header className="war-hero shell"><div><p className="eyebrow"><span/> مكتب إقليمي مباشر · 20 يوليو 2026</p><h1>حرب إيران وإسرائيل<br/><em>وأميركا، مباشر.</em></h1><p>تحديثات سريعة بمصادر ظاهرة، وخريطة للانكشاف الإقليمي، واهتمام بالمدنيين في إيران وفلسطين ولبنان واليمن والمنطقة العربية الأوسع.</p><a href="#live">افتح التحديثات المباشرة ↓</a></div><aside><b><i/> الإشارة الحالية</b><h2>اتساع القتال مع طرح الوسطاء هدنة لعشرة أيام.</h2><p>تفيد رويترز بليلة تاسعة متتالية من الضربات الأميركية، ورد إيراني، وتهديد حوثي بفتح جبهة بحرية إضافية.</p><a href="https://www.reuters.com/world/middle-east/us-launches-iran-strikes-ninth-day-another-american-confirmed-killed-2026-07-20/" target="_blank" rel="noreferrer">اقرأ المصدر ↖</a></aside></header>
 <section className="war-map-section"><div className="shell"><div className="war-map-head"><div><p className="eyebrow light"><span/> خريطة انكشاف الدول</p><h2>عالم من النقاط،<br/><em>تلونه مستويات التصعيد.</em></h2></div><p>هذه مستويات تحريرية من وورلدلاين بناءً على القتال المباشر والضربات المعلنة والقواعد العسكرية وطرق الشحن والتداعيات القريبة. ليست نصيحة سفر ولا تنبؤاً.</p></div><div className="war-map-frame"><WarDotMap/><span>20 يوليو · 2026</span></div><div className="war-legend">{groups.map(g=><article className={g.className} key={g.className}><i/><small>{g.label}</small><h3>{g.countries}</h3><p>{g.note}</p></article>)}</div></div></section>
 <section className="war-live shell" id="live"><div className="section-heading"><div><p className="eyebrow"><span/> تغذية تلقائية · تخزين 5 دقائق</p><h2>أحدث التقارير.</h2></div><p>تُسحب العناوين من فهرس GDELT المفتوح، مع Google News RSS ولقطة موثقة بتاريخ 20 يوليو كبدائل. تفتح الروابط لدى الناشر الأصلي.</p></div><LiveWarNews lang="ar"/></section>
 <section className="war-sources"><div className="shell"><div><b>لقطة موثقة</b><h2>ما هو مؤكد الآن.</h2></div><ol><li><span>01</span><p>تفيد رويترز بأن وسطاء اقترحوا وقفاً لإطلاق النار لعشرة أيام لإحياء الاتفاق الإيراني الأميركي المؤقت.</p><a href="https://www.reuters.com/world/middle-east/mediators-propose-10-day-ceasefire-revive-iran-us-interim-deal-senior-iranian-2026-07-20/" target="_blank" rel="noreferrer">رويترز ↖</a></li><li><span>02</span><p>حددت أسوشيتد برس هوية جنديين أميركيين قُتلا في هجمات إيرانية بالأردن.</p><a href="https://apnews.com/article/1fd99826dfd511913b63d0b033b262d9" target="_blank" rel="noreferrer">أسوشيتد برس ↖</a></li><li><span>03</span><p>حث الأمين العام للأمم المتحدة إيران والولايات المتحدة على العودة العاجلة إلى الدبلوماسية.</p><a href="https://www.un.org/sg/en/content/highlight/2026-07-13.html" target="_blank" rel="noreferrer">الأمم المتحدة ↖</a></li></ol></div></section>
 <section className="war-method shell"><b>منهج الخريطة</b><p>الخريطة واسعة ومحررة عمداً. الأحمر يعني طرفاً مباشراً أو جبهة نشطة متصلة، والبرتقالي يعني انكشافاً عسكرياً أو على البنية التحتية أو الشحن، والأصفر يعني تداعيات محدودة أو قرباً من الوساطة، والرمادي يعني خارج هذا المتتبع. لون الدولة لا يعني تساوي الخطر في جميع مناطقها.</p></section>
 <footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>المدنيون أولاً. المصادر ظاهرة.</p><p>© 2026 وورلدلاين</p></footer>
 </main>}
