import type { Metadata } from "next";import {notFound} from "next/navigation";import news from "../../../../data/news-ar.json";
type Article=(typeof news)[number];export function generateStaticParams(){return news.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=news.find(i=>i.slug===slug);return a?{title:`${a.title} — وورلدلاين`,description:a.dek}:{}}
export default async function ArabicArticle({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=news.find(i=>i.slug===slug) as Article|undefined;if(!a)notFound();const related=news.filter(i=>i.slug!==a.slug).slice(0,3);return <main className="article-page ar-page" dir="rtl" lang="ar">
<nav className="nav shell article-nav"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/ar#latest">الأحدث</a><a href="/ar/gaza">غزة</a><a href={`/news/${a.slug}`}>English</a></div><a className="edition" href="/ar#latest">العودة لكل القصص <span>→</span></a></nav>
<article><header className="article-header shell"><div className="article-kicker"><span>{a.number}</span><b>{a.category}</b><time>{a.date}</time></div><h1>{a.title}</h1><p className="article-dek">{a.dek}</p><div className="article-byline"><span>بقلم {a.author}</span><span>{a.readTime}</span></div></header>
<div className="article-visual shell"><div className="mini-globe"><span/><i/><b/></div><p>{a.category}</p><strong>{a.number}</strong></div>
<div className="article-body shell"><aside><span>الخلاصة</span><ul>{a.keyPoints.map(p=><li key={p}>{p}</li>)}</ul></aside><div className="article-copy">{a.paragraphs.map((p,i)=><p className={i===0?"first-paragraph":""} key={p}>{p}</p>)}<div className="source-card"><span>المصدر الأساسي</span><p>هذا الملخص من إعداد وورلدلاين استناداً إلى تغطية {a.source}.</p><a href={a.sourceUrl} target="_blank" rel="noreferrer">اقرأ المصدر الأصلي ↖</a></div></div></div></article>
<section className="related shell"><p className="eyebrow"><span/> تابع القراءة</p><div className="related-grid">{related.map(i=><a href={`/ar/news/${i.slug}`} key={i.slug}><span>{i.category}</span><h2>{i.title}</h2><b>اقرأ القصة ↖</b></a>)}</div></section>
<footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>صحافة مستقلة للعقول الفضولية.</p><p>© 2026 وورلدلاين</p></footer></main>}