import {NextRequest,NextResponse} from "next/server";

export const runtime="nodejs";
type Raw={url?:string;title?:string;seendate?:string;socialimage?:string;domain?:string;sourcecountry?:string};
const fallback={
 en:[
  {title:"Houthis announce Saudi naval blockade, threatening a wider front",url:"https://www.reuters.com/world/middle-east/us-launches-iran-strikes-ninth-day-another-american-confirmed-killed-2026-07-20/",source:"Reuters",publishedAt:"2026-07-20T15:00:00Z",image:"",country:"Middle East"},
  {title:"Mediators propose a 10-day ceasefire to revive an Iran–U.S. interim deal",url:"https://www.reuters.com/world/middle-east/mediators-propose-10-day-ceasefire-revive-iran-us-interim-deal-senior-iranian-2026-07-20/",source:"Reuters",publishedAt:"2026-07-20T13:00:00Z",image:"",country:"Iran / U.S."},
  {title:"After a deadly weekend for U.S. troops, Trump vows retaliation",url:"https://www.reuters.com/world/middle-east/after-deadly-weekend-us-troops-trump-vows-revenge-against-iran-2026-07-20/",source:"Reuters",publishedAt:"2026-07-20T11:00:00Z",image:"",country:"United States"},
  {title:"U.S. soldiers killed by Iran in Jordan identified",url:"https://apnews.com/article/1fd99826dfd511913b63d0b033b262d9",source:"AP",publishedAt:"2026-07-20T10:00:00Z",image:"",country:"Jordan"},
  {title:"U.S. gasoline prices cross $4 as fighting disrupts oil shipments",url:"https://www.reuters.com/business/energy/us-pump-prices-cross-4-again-renewed-fighting-middle-east-2026-07-20/",source:"Reuters",publishedAt:"2026-07-20T09:00:00Z",image:"",country:"Global economy"},
  {title:"UN Secretary-General urges Iran and the United States to resume negotiations",url:"https://www.un.org/sg/en/content/highlight/2026-07-13.html",source:"United Nations",publishedAt:"2026-07-13T12:00:00Z",image:"",country:"Diplomacy"}
 ],
 ar:[
  {title:"الحوثيون يعلنون حصاراً بحرياً على السعودية بما يهدد بتوسيع جبهة الحرب",url:"https://www.reuters.com/world/middle-east/us-launches-iran-strikes-ninth-day-another-american-confirmed-killed-2026-07-20/",source:"رويترز",publishedAt:"2026-07-20T15:00:00Z",image:"",country:"الشرق الأوسط"},
  {title:"وسطاء يقترحون وقفاً لإطلاق النار لمدة 10 أيام لإحياء اتفاق إيراني أميركي",url:"https://www.reuters.com/world/middle-east/mediators-propose-10-day-ceasefire-revive-iran-us-interim-deal-senior-iranian-2026-07-20/",source:"رويترز",publishedAt:"2026-07-20T13:00:00Z",image:"",country:"إيران / أميركا"},
  {title:"ترامب يتوعد بالرد بعد عطلة دامية للقوات الأميركية",url:"https://www.reuters.com/world/middle-east/after-deadly-weekend-us-troops-trump-vows-revenge-against-iran-2026-07-20/",source:"رويترز",publishedAt:"2026-07-20T11:00:00Z",image:"",country:"الولايات المتحدة"},
  {title:"تحديد هوية جنديين أميركيين قُتلا في هجوم إيراني بالأردن",url:"https://apnews.com/article/1fd99826dfd511913b63d0b033b262d9",source:"أسوشيتد برس",publishedAt:"2026-07-20T10:00:00Z",image:"",country:"الأردن"},
  {title:"أسعار البنزين الأميركية تتجاوز 4 دولارات مع اضطراب شحنات النفط",url:"https://www.reuters.com/business/energy/us-pump-prices-cross-4-again-renewed-fighting-middle-east-2026-07-20/",source:"رويترز",publishedAt:"2026-07-20T09:00:00Z",image:"",country:"الاقتصاد العالمي"},
  {title:"الأمم المتحدة تحث إيران والولايات المتحدة على استئناف المفاوضات",url:"https://www.un.org/sg/en/content/highlight/2026-07-13.html",source:"الأمم المتحدة",publishedAt:"2026-07-13T12:00:00Z",image:"",country:"الدبلوماسية"}
 ]
};
function iso(v=""){const m=v.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/);return m?`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`:v||new Date().toISOString()}
function clean(v=""){return v.replace(/^<!\[CDATA\[|\]\]>$/g,"").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim()}
function tag(block:string,name:string){return clean(block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`,"i"))?.[1]||"")}
async function rss(lang:"en"|"ar"){
 const u=new URL("https://news.google.com/rss/search");u.searchParams.set("q",lang==="ar"?"إيران إسرائيل الولايات المتحدة الحرب when:2d":"Iran Israel United States war when:2d");u.searchParams.set("hl",lang==="ar"?"ar":"en-US");u.searchParams.set("gl",lang==="ar"?"JO":"US");u.searchParams.set("ceid",lang==="ar"?"JO:ar":"US:en");
 const response=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0 WorldlineWarDesk/1.0"}});if(!response.ok)throw new Error("RSS");const xml=await response.text();const seen=new Set<string>();const articles=Array.from(xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)).map(m=>m[1]).map(item=>{const title=tag(item,"title"),url=tag(item,"link"),source=tag(item,"source")||"Google News",date=tag(item,"pubDate");return{title,url,source,publishedAt:date?new Date(date).toISOString():new Date().toISOString(),image:"",country:lang==="ar"?"إقليمي":"Regional"}}).filter(a=>a.title&&a.url&&a.title.length>20).filter(a=>{const k=a.title.toLowerCase().replace(/\W/g,"").slice(0,90);if(seen.has(k))return false;seen.add(k);return true}).slice(0,24);if(!articles.length)throw new Error("empty");return articles;
}
export async function GET(request:NextRequest){const lang=request.nextUrl.searchParams.get("lang")==="ar"?"ar":"en";try{
 const query=lang==="ar"?'(إيران AND (إسرائيل OR أمريكا OR "الولايات المتحدة")) sourcelang:arabic':'((Iran AND (Israel OR "United States" OR US)) OR "Iran war") sourcelang:english';const u=new URL("https://api.gdeltproject.org/api/v2/doc/doc");u.searchParams.set("query",query);u.searchParams.set("mode","artlist");u.searchParams.set("maxrecords","50");u.searchParams.set("format","json");u.searchParams.set("sort","datedesc");u.searchParams.set("timespan","2d");
 const response=await fetch(u,{headers:{"User-Agent":"Worldline-War-News/1.0"}});if(!response.ok)throw new Error("GDELT");const data=await response.json() as {articles?:Raw[]};const seen=new Set<string>();const articles=(data.articles||[]).filter(a=>a.url&&a.title&&a.title.length>20).filter(a=>{const k=a.title!.toLowerCase().replace(/\W/g,"").slice(0,90);if(seen.has(k))return false;seen.add(k);return true}).slice(0,24).map(a=>({title:a.title!,url:a.url!,source:a.domain||new URL(a.url!).hostname.replace(/^www\./,""),publishedAt:iso(a.seendate),image:a.socialimage||"",country:a.sourcecountry||(lang==="ar"?"إقليمي":"Regional")}));if(!articles.length)throw new Error("empty");return NextResponse.json({articles,updatedAt:new Date().toISOString(),provider:"GDELT",live:true},{headers:{"Cache-Control":"public, s-maxage=300, stale-while-revalidate=1200"}})
 }catch{try{return NextResponse.json({articles:await rss(lang),updatedAt:new Date().toISOString(),provider:"Google News RSS",live:true},{headers:{"Cache-Control":"public, s-maxage=300, stale-while-revalidate=1200"}})}catch{return NextResponse.json({articles:fallback[lang],updatedAt:new Date().toISOString(),provider:"Verified snapshot",live:false},{headers:{"Cache-Control":"public, s-maxage=300, stale-while-revalidate=1200"}})}}}
