import chapters from "../../../data/palestine-ar.json";
export const metadata={title:"فلسطين: الأرض والذاكرة والحياة — وورلدلاين",description:"دليل فلسطيني المنظور للتاريخ والنكبة والحياة والقدس والأرض وغزة."};
export default function PalestineHubAr(){return <main className="palestine-hub ar-page" dir="rtl" lang="ar">
  <nav className="nav shell palestine-nav"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/ar">الرئيسية</a><a className="active" href="/ar/palestine">فلسطين</a><a href="/ar/gaza">غزة</a><a href="/palestine">English</a></div><a className="edition" href="#chapters">ستة فصول <span>↓</span></a></nav>
  <header className="palestine-hero shell"><div><p className="eyebrow"><span/> الأرض · الذاكرة · الحياة</p><h1>فلسطين،<br/><em>قصة كاملة.</em></h1><p>من المدن القديمة والنكبة إلى الثقافة الحية اليوم: تاريخ فلسطيني للبيت والقدس والزيتون والتين، وللمطالبة بالحرية.</p><a href="#map">ابدأ بالخريطة <span>↙</span></a></div><div className="palestine-word" aria-hidden="true"><b>فلسطين</b><span>Palestine</span></div></header>
  <section className="palestine-map" id="map"><div className="shell map-grid"><figure><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Map%20of%20Mandatory%20Palestine%20in%201946%20with%20major%20cities%20(in%20Arabic).svg" alt="خريطة فلسطين تحت الانتداب عام 1946 وتظهر المدن الرئيسية"/><figcaption><span>خريطة مرجعية تاريخية · 1946</span><a href="https://commons.wikimedia.org/wiki/File:Map_of_Mandatory_Palestine_in_1946_with_major_cities_(in_Arabic).svg" target="_blank" rel="noreferrer">ويكيميديا كومنز ↗</a></figcaption></figure><div><p className="eyebrow light"><span/> اقرأ الأرض</p><h2>بلد من المدن والقرى والطرق.</h2><p>تسجل هذه الخريطة فلسطين سنة 1946 قبل النكبة مباشرة. هي خريطة تاريخية وليست اقتراحاً لحدود اليوم، وتذكير بأن الأرض كانت مسماة ومخططة ومأهولة.</p><ul><li><b>الساحل</b><span>غزة · يافا · حيفا · عكا</span></li><li><b>الجبال</b><span>القدس · نابلس · الخليل</span></li><li><b>الجليل</b><span>صفد · طبريا · الناصرة</span></li></ul></div></div></section>
  <section className="palestine-intro shell"><p className="eyebrow"><span/> موقفنا التحريري</p><blockquote>التاريخ الفلسطيني ليس هامشاً، والبيوت الفلسطينية ليست قابلة للمحو، والحرية الفلسطينية ليست مشروطة.</blockquote><p>نكتب من منظور حقوقي فلسطيني. ترتبط الحقائق والادعاءات القانونية بمصادر أممية وقضائية ودولية، ونوضح النتائج القانونية محل النزاع.</p></section>
  <section className="palestine-chapters shell" id="chapters"><div className="section-heading"><div><p className="eyebrow"><span/> دليل من ستة فصول</p><h2>القصة، فصلاً بعد فصل.</h2></div><p>التاريخ والاقتلاع والثقافة والقدس والزيتون والتين وغزة في مكان واحد.</p></div>{chapters.map(c=><a className="palestine-card" href={`/ar/palestine/${c.slug}`} key={c.slug}><span>{c.number}</span><div><b>{c.eyebrow}</b><h2>{c.title}</h2><p>{c.dek}</p></div><i>اقرأ الفصل ↖</i></a>)}</section>
  <footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>الأرض · الذاكرة · الكرامة.</p><p>© 2026 وورلدلاين</p></footer>
  </main>}
