import type { Metadata } from "next";
import WLBScanner from "../components/WLBScanner";
import { boycottEntries, levelCopy, type BoycottLevel } from "../../data/boycott";

export const metadata:Metadata={title:"WLB Boycott Scanner — Worldline",description:"Scan a barcode, identify the product, and check an evidence-backed boycott directory."};
const groups:BoycottLevel[]=["priority","organic","pressure","community"];

export default function WLBPage(){return <main className="wlb-page">
  <nav className="nav shell wlb-nav"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="#scanner">Scanner</a><a href="#directory">Directory</a><a href="#method">Method</a><a href="/research/palestine">Palestine</a></div><a className="edition" href="/ar/wlb">العربية ↗</a></nav>
  <header className="wlb-hero shell"><div><p className="eyebrow"><span/> Worldline Boycott · WLB</p><h1>Scan.<br/><em>Know.</em><br/>Choose.</h1></div><aside><b>PEACEFUL CONSUMER ACTION</b><p>An evidence-led guide for people who want their spending to align with Palestinian rights.</p><a href="#scanner">Open the scanner ↓</a></aside></header>
  <section className="wlb-scan-section" id="scanner"><div className="shell wlb-scan-grid"><div><p className="eyebrow light"><span/> Barcode intelligence</p><h2>What is in<br/>your hand?</h2><p>WLB searches three open product catalogues, checks brand names against a transparent directory, and explains every match.</p><div className="scanner-rule"><b>IMPORTANT</b><p>A barcode prefix is not proof of where a product was made. GS1 says it identifies the organization that allocated the number.</p></div></div><WLBScanner lang="en"/></div></section>
  <section className="wlb-directory shell" id="directory"><div className="wlb-section-head"><div><p className="eyebrow"><span/> Evidence directory</p><h2>Not one list.<br/><em>Four clear levels.</em></h2></div><p>WLB keeps official priority targets separate from pressure campaigns and broader community calls. That distinction matters.</p></div>
    {groups.map(level=><div className="directory-group" key={level}><div><span>{String(groups.indexOf(level)+1).padStart(2,"0")}</span><h3>{levelCopy[level].en}</h3><p>{level==="community"?"Community campaigns included with an explicit evidence note.":"Classification follows the BDS movement guide linked in each entry."}</p></div><div>{boycottEntries.filter(e=>e.level===level).map(entry=><article key={entry.id}><b>{entry.name}</b>{entry.parent&&<small>{entry.parent}</small>}<p>{entry.reason.en}</p><a href={entry.sources[0].url} target="_blank" rel="noreferrer">Evidence ↗</a></article>)}</div></div>)}
  </section>
  <section className="wlb-method" id="method"><div className="shell"><div><p className="eyebrow light"><span/> How to read a result</p><h2>Evidence before<br/>a red label.</h2></div><ol><li><b>01</b><span>Product data</span><p>Open Food Facts, Open Beauty Facts and Open Products Facts supply community-maintained names, brands and images.</p></li><li><b>02</b><span>Brand match</span><p>WLB compares reported brands with documented aliases and parent-brand relationships in this directory.</p></li><li><b>03</b><span>Human judgment</span><p>Open data can be incomplete. “No match” never means certified safe; verify high-stakes choices with the linked evidence.</p></li></ol></div></section>
  <footer className="footer shell"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><p>WLB supports informed, peaceful consumer choice—never harassment.</p><p>© 2026 Worldline Journal</p></footer>
  </main>}
