import chapters from "../../data/palestine.json";

export const metadata={title:"Palestine: Land, Memory, Life — Worldline",description:"A Palestinian-centered guide to history, the Nakba, life, Al-Quds, land and Gaza."};

export default function PalestineHub(){return <main className="palestine-hub">
  <nav className="nav shell palestine-nav"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/">Home</a><a className="active" href="/palestine">Palestine</a><a href="/gaza">Gaza</a><a href="/ar/palestine">العربية</a></div><a className="edition" href="#chapters">Six chapters <span>↓</span></a></nav>
  <header className="palestine-hero shell"><div><p className="eyebrow"><span/> Land · memory · life</p><h1>Palestine,<br/><em>remembered whole.</em></h1><p>From ancient cities and the Nakba to the living culture of today: a Palestinian-centered history of home, القدس, olive and fig—and the demand for freedom.</p><a href="#map">Begin with the map <span>↘</span></a></div><div className="palestine-word" aria-hidden="true"><b>فلسطين</b><span>Palestine</span></div></header>
  <section className="palestine-map" id="map"><div className="shell map-grid"><figure><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Map%20of%20Mandatory%20Palestine%20in%201946%20with%20major%20cities%20(in%20English).svg" alt="Map of Mandatory Palestine in 1946 showing major cities"/><figcaption><span>Historic reference map · 1946</span><a href="https://commons.wikimedia.org/wiki/File:Map_of_Mandatory_Palestine_in_1946_with_major_cities_(in_English).svg" target="_blank" rel="noreferrer">Bolter21 / CC BY-SA 4.0 ↗</a></figcaption></figure><div><p className="eyebrow light"><span/> Read the land</p><h2>A country of cities, villages and roads.</h2><p>This 1946 map records Palestine immediately before the Nakba. It is a historical map—not a proposal for today’s borders—and a reminder that the land was named, mapped and densely lived.</p><ul><li><b>Coast</b><span>Gaza · Yafa · Haifa · Akka</span></li><li><b>Highlands</b><span>Al-Quds · Nablus · Al-Khalil</span></li><li><b>Galilee</b><span>Safad · Tiberias · Nazareth</span></li></ul></div></div></section>
  <section className="palestine-intro shell"><p className="eyebrow"><span/> Editorial position</p><blockquote>Palestinian history is not a footnote, Palestinian homes are not disposable, and Palestinian freedom is not conditional.</blockquote><p>We write from a Palestinian human-rights perspective. Facts and legal claims link to UN, court and international institutional sources; contested legal findings are labelled as such.</p></section>
  <aside className="truth-banner shell"><b>The true story, in photographs.</b><p>Graphic documentary images of blood, injury, covered bodies and bombed homes. Viewer discretion advised.</p><a href="/palestine/the-true-story">Open warned record ↗</a></aside>\n  <section className="palestine-chapters shell" id="chapters"><div className="section-heading"><div><p className="eyebrow"><span/> Six-part guide</p><h2>The story, chapter by chapter.</h2></div><p>History, dispossession, culture, Al-Quds, the olive and fig, and Gaza—connected in one place.</p></div>{chapters.map(c=><a className="palestine-card" href={`/palestine/${c.slug}`} key={c.slug}><span>{c.number}</span><div><b>{c.eyebrow}</b><h2>{c.title}</h2><p>{c.dek}</p></div><i>Read chapter ↗</i></a>)}</section>
  <footer className="footer shell"><a className="brand" href="/">WORLD<span>LINE</span><i/></a><p>Land · memory · dignity.</p><p>© 2026 Worldline Journal</p></footer>
  </main>}
