export const metadata={title:"القصة الحقيقية: غزة بالصور — وورلدلاين",description:"سجل وثائقي مع تحذير ومصادر للإصابات والموت والبيوت المدمرة في غزة."};
const images=[
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Damage%20in%20Gaza%20Strip%20during%20the%20October%202023%20-%2029.jpg",alt:"فلسطينيون بين بيوت دمرتها غارة إسرائيلية في حي الرمال بمدينة غزة",title:"البيت بعد القنبلة",caption:"دمار في حي الرمال بمدينة غزة بعد غارة إسرائيلية، 9 أكتوبر 2023.",credit:"نعمان عمر / APAimages عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Damage_in_Gaza_Strip_during_the_October_2023_-_29.jpg",kind:"بيوت مدمرة"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Fars%20Photo%20of%20Casualties%20in%20Gaza%20Strip%20during%202023%20War%2031.jpg",alt:"طفل فلسطيني مصاب بعد غارات إسرائيلية على غزة",title:"الطفل ليس رقماً",caption:"طفل فلسطيني مصاب في غزة، صُوّر في أكتوبر 2023.",credit:"غسان سالم / فارس ميديا عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Fars_Photo_of_Casualties_in_Gaza_Strip_during_2023_War_31.jpg",kind:"دم وإصابة"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Relatives%20of%20Palestinians%20who%20died%20in%20Israeli%20airstrikes%20gathering%20around%20the%20bodies%20taken%20from%20the%20morgue%20of%20Al-Aqsa%20Martyrs%20hospital%20in%20Deir%20el-Balah%2C%20Gaza.jpg",alt:"أقارب فلسطينيون مفجوعون يحيطون بجثامين مغطاة أمام مستشفى شهداء الأقصى في دير البلح",title:"يترك الموتى عائلات خلفهم",caption:"أقارب يحيطون بجثامين أُخرجت من مشرحة مستشفى شهداء الأقصى في دير البلح، 6 نوفمبر 2023.",credit:"أشرف عمرة / الأونروا عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Relatives_of_Palestinians_who_died_in_Israeli_airstrikes_gathering_around_the_bodies_taken_from_the_morgue_of_Al-Aqsa_Martyrs_hospital_in_Deir_el-Balah,_Gaza.jpg",kind:"جثامين مغطاة وفقد"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Images%20of%20war%2023-25%20from%20Gaza%2C%20by%20Jaber%20Badwen%2C%20IMG%206185.jpg",alt:"أنقاض بيوت في بيت لاهيا دمرها القصف الإسرائيلي",title:"حي تحول إلى ركام",caption:"أنقاض بيت لاهيا شمال غزة، 23 فبراير 2025.",credit:"جابر جهاد بدوان عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Images_of_war_23-25_from_Gaza,_by_Jaber_Badwen,_IMG_6185.jpg",kind:"حي مقصوف"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Damage%20in%20Gaza%20Strip%20during%20the%20October%202023%20-%2006.jpg",alt:"فلسطينيون يتفقدون أنقاض برج وطن بعد غارات إسرائيلية في مدينة غزة",title:"حيث كانت تعيش العائلات",caption:"فلسطينيون يتفقدون برج وطن بعد تدميره في غارات إسرائيلية، مدينة غزة، 8 أكتوبر 2023.",credit:"نعمان عمر / APAimages عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Damage_in_Gaza_Strip_during_the_October_2023_-_06.jpg",kind:"برج سكني مدمر"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Fars%20Photo%20of%20Casualties%20in%20Gaza%20Strip%20during%202023%20War%2026.jpg",alt:"مسعف يحمل طفلاً فلسطينياً مصاباً في غزة",title:"محمولاً نحو العلاج",caption:"مسعف يحمل طفلاً فلسطينياً مصاباً في غزة في أكتوبر 2023.",credit:"غسان سالم / فارس ميديا عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Fars_Photo_of_Casualties_in_Gaza_Strip_during_2023_War_26.jpg",kind:"طفل مصاب"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Fars%20Photo%20of%20Casualties%20in%20Gaza%20Strip%20during%202023%20War%2003.jpg",alt:"فلسطينيون قتلوا في غزة داخل أكياس جثامين مغطاة",title:"انتهت حياتهم وبقيت أسماؤهم",caption:"جثامين مغطاة في غزة عقب سقوط أعداد كبيرة من الضحايا في أكتوبر 2023.",credit:"صالح نجم وأنس الشريف / فارس ميديا عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Fars_Photo_of_Casualties_in_Gaza_Strip_during_2023_War_03.jpg",kind:"جثامين مغطاة"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Forced%20Displacement%20of%20Gaza%20Strip%20Residents%20During%20the%20Gaza-Israel%20War%2023-25.jpg",alt:"عائلات فلسطينية مهجرة تعبر منطقة دمرها القصف في غزة",title:"من ركام إلى ركام",caption:"فلسطينيون مهجرون يعبرون منطقة مدمرة في غزة، 29 يناير 2025.",credit:"جابر جهاد بدوان عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Forced_Displacement_of_Gaza_Strip_Residents_During_the_Gaza-Israel_War_23-25.jpg",kind:"تهجير قسري"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Palestine%20Red%20Crescent%20Society%27s%20ambulance%20after%20being%20targeted%20by%20Israeli%20missile%20in%20Khan%20Yunis.png",alt:"مركبة إسعاف تابعة للهلال الأحمر الفلسطيني متضررة بشدة أمام مستشفى ناصر في خان يونس",title:"حتى سيارة الإسعاف ضُربت",caption:"مركبة إسعاف للهلال الأحمر الفلسطيني متضررة أمام مستشفى ناصر في خان يونس، 7 أكتوبر 2023.",credit:"لقطات تسنيم عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Palestine_Red_Crescent_Society%27s_ambulance_after_being_targeted_by_Israeli_missile_in_Khan_Yunis.png",kind:"نقل طبي متضرر"},
 {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Israeli%20destruction%20on%20al-Seqaly%20Street%20in%20Khan%20Younis%2C%20Gaza%20War%2C%20June%2011%202024.jpg",alt:"مبان مدمرة وركام في شارع الصقلي بخان يونس",title:"شارع مُحي",caption:"دمار في شارع الصقلي بخان يونس، 11 يونيو 2024.",credit:"Rawanmurad2025 عبر ويكيميديا كومنز",page:"https://commons.wikimedia.org/wiki/File:Israeli_destruction_on_al-Seqaly_Street_in_Khan_Younis,_Gaza_War,_June_11_2024.jpg",kind:"شارع مدمر"}
];
export default function TrueStoryAr(){return <main className="truth-page ar-page" dir="rtl" lang="ar">
 <nav className="nav shell truth-nav"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><div className="nav-links"><a href="/ar">الرئيسية</a><a href="/ar/palestine">فلسطين</a><a href="/ar/gaza">غزة</a><a href="/palestine/the-true-story">English</a></div><a className="edition" href="/ar/palestine">العودة للدليل <span>→</span></a></nav>
 <header className="truth-head shell"><p className="eyebrow"><span/> سجل وثائقي</p><h1>القصة الحقيقية<br/><em>لها شهود.</em></h1><p>تُظهر هذه الصور ما قد تخففه الكلمات: الدم والأطفال المصابين والجثامين العائدة إلى العائلات والبيوت التي تحولت إلى ركام في غزة.</p><div className="truth-warning"><b>تحذير من محتوى صادم</b><span>تحتوي الصفحة على صور وثائقية للدم وأطفال مصابين وجثامين مغطاة. تابع فقط إذا اخترت رؤيتها.</span></div></header>
 <section className="truth-context shell"><b>لماذا ننشر هذه الصور؟</b><p>ليس بهدف الصدمة. الضحايا والجرحى بشر، وليسوا مادة بصرية للاستهلاك. ننشر سجلاً محدوداً وموثقاً لأن اللغة المعقمة قد تخفي النتيجة الإنسانية للقصف. ولا تقول التعليقات أكثر مما يدعمه المصدر.</p></section>
 <details className="truth-reveal shell"><summary><span>أفهم التحذير — أظهر الصور الوثائقية</span><b>افتح السجل ↓</b></summary><div className="truth-gallery">{images.map((img,i)=><figure className="truth-image" key={img.src}><div><img src={img.src} alt={img.alt}/><span>{String(i+1).padStart(2,"0")} / {img.kind}</span></div><figcaption><h2>{img.title}</h2><p>{img.caption}</p><a href={img.page} target="_blank" rel="noreferrer">{img.credit} ↗</a></figcaption></figure>)}</div></details>
 <section className="truth-close shell"><p className="eyebrow"><span/> تذكّر الإنسان</p><blockquote>كل جثمان كان ابناً أو ابنة أو أباً أو أماً أو أخاً أو صديقاً أو جاراً. وكل بيت مدمر احتوى حياة أكبر من الركام.</blockquote><a href="/ar/palestine/gaza-genocide-and-the-duty-to-protect">اقرأ فصل غزة الموثق ↖</a></section>
 <footer className="footer shell"><a className="brand" href="/ar">WORLD<span>LINE</span><i/></a><p>توثيق بكرامة.</p><p>© 2026 وورلدلاين</p></footer>
 </main>}
